In [1]:
import numpy as np

# Creating matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


In [2]:
# Adding two matrices
result = A + B
print("Matrix Addition:\n", result)


Matrix Addition:
 [[ 6  8]
 [10 12]]


In [3]:
# Subtracting two matrices
result = A - B
print("Matrix Subtraction:\n", result)


Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]


In [4]:
# Element-wise multiplication
result = A * B
print("Element-wise Multiplication:\n", result)


Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


In [5]:
# Matrix multiplication
result = np.dot(A, B)
print("Matrix Dot Product (Multiplication):\n", result)


Matrix Dot Product (Multiplication):
 [[19 22]
 [43 50]]


In [6]:
# Transposing a matrix
result = A.T
print("Transpose of A:\n", result)


Transpose of A:
 [[1 3]
 [2 4]]


In [7]:
# Determinant of a matrix
determinant = np.linalg.det(A)
print("Determinant of A:", determinant)


Determinant of A: -2.0000000000000004


In [8]:
# Inverse of a matrix
inverse = np.linalg.inv(A)
print("Inverse of A:\n", inverse)


Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)


Eigenvalues of A: [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [10]:
# Trace of a matrix (sum of diagonal elements)
trace = np.trace(A)
print("Trace of A:", trace)


Trace of A: 5


In [11]:
# Solving Ax = B for x
B = np.array([10, 14])  # Modify B for a valid system
x = np.linalg.solve(A, B)
print("Solution x:", x)


Solution x: [-6.  8.]
