### Array (ndarray) creation using array module 

In [3]:
import array
a = array.array('i', [10, 20, 30]) # i represent int type array
print(f"Type of a: {type(a)}")
print(f"a value ==> {a}") 
print("Elements one by one") 

for i in range(len(a)):
    print(a[i])

Type of a: <class 'array.array'>
a value ==> array('i', [10, 20, 30])
Elements one by one
10
20
30


### Array (ndarray) creation using Numpy 

1. `array() `
2. `arange() `
3. `linspace() `
4. `zeros() `
5. `ones() `
6. `full() `
7. `eye() `
8. `identity() `
9. `diag() `
10. `empty()`
11. `np.random` module 
    , `randint()` 
    , `rand()` 
    , `uniform()` 
    , `randn()` 
    , `normal()` 
    , `shuffle()`

### Note: 
 
- np.random module is developed based on array. 
- So performance of this module is more when compared with normal python 
random module

![img](./images/ndarraay.png)

### 1-D array(Vector) creation using list or tuple 

In [4]:
# 1-D array creation from list or tuple 
l = [10,20,30] 
print(f'Type of l ==> {type(l)}') 
a = np.array(l) 
print(f'Type of a ==> {type(a)}') 
print(f"a ==>  {a}") 

Type of l ==> <class 'list'>
Type of a ==> <class 'numpy.ndarray'>
a ==>  [10 20 30]


### To know properties of ndarray 
- `np.ndim` ==> to know the dimension of the ndarray 
- `np.dtype` ==> to know the data type of the elements in the ndarray 
- `np.size` ==> to know the total number of elements in the array. 
- `np.shape` ==> returns the shape of an array in tuple form 

In [9]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(3,)
3
int32


In [10]:
# 1-D array creating using tuples 
t = ('krishna','nandu','moneesh') 

print(f'Type of t ==> {type(t)}') 
a = np.array(t) 

print(f'Type of a ==> {type(a)}') 
print(f'The data type of elements of array a ==> {a.dtype}') 
print(f'The size of the array a ==> {a.size}') 
print(f'The shape of the array a ==> {a.shape}') 
print(f"a ==> {a}")

Type of t ==> <class 'tuple'>
Type of a ==> <class 'numpy.ndarray'>
The data type of elements of array a ==> <U7
The size of the array a ==> 3
The shape of the array a ==> (3,)
a ==> ['krishna' 'nandu' 'moneesh']


### 2-D array(Matrix) creation using Nested Lists 

In [24]:
# [[10,20,30],[40,50,60],[70,80,90]] --->Nested List 
a = np.array([[10,20,30],[40,50,60],[70,80,90]]) 
print(f'Type of a ==> {type(a)}') 
print(f'\n{a}\n') 
print(f'dimensions of a: {a.ndim}') 
print(f'The data type of elements : {a.dtype}') 
print(f'The size of the array a : {a.size}') 
print(f'The shape of the array a : {a.shape}')


Type of a ==> <class 'numpy.ndarray'>

[[10 20 30]
 [40 50 60]
 [70 80 90]]

dimensions of a: 2
The data type of elements : int32
The size of the array a : 9
The shape of the array a : (3, 3)


Array contains only homogenous elements 

- If list contains heterogenous elements, and while creating the array upcasting 
will be performed. 

In [25]:
# list contains heterogenous elements 
l = [10,20,30.5] 
a = np.array(l) # upcasting to float  
print(f'a :: {a}') 
print(f'data type of elements of a : {a.dtype}') 

a :: [10.  20.  30.5]
data type of elements of a : float64


Creating arrays with particular datatype 
- we have to use dtype argument while creating the arrray

In [17]:
# int type 
a = np.array([10,20,30.5],dtype=int) 
print(a) 

[10 20 30]


In [18]:
# float type 
a = np.array([10,20,30.5],dtype=float) 
print(a)

[10.  20.  30.5]


In [19]:
# bool type ==> any number is True and zero is False. Any string is True and empty string is False 
a = np.array([10,20,30.5],dtype=bool) 
print(a)

[ True  True  True]


In [20]:
# complex type 
a = np.array([10,20,30.5,0],dtype=complex) 
print(a)

[10. +0.j 20. +0.j 30.5+0.j  0. +0.j]


In [21]:
# str type 
a = np.array([10,20,30.5],dtype=str) 
print(a) 

['10' '20' '30.5']


creating object type array 
- object is the parent of all int, float, bool, complex and str 
- Here the elements are looks like heterogeneous. But the datatype of elements is 
'object' 

In [22]:
a = np.array([10,'krishna',10.5,True,10+20j],dtype=object) 
print(a) 
 
# data type 
print(f"Data type of elements of array a ==> {a.dtype}")

[10 'krishna' 10.5 True (10+20j)]
Data type of elements of array a ==> object


`arange()`
- • we can create only 1-D arrays with arange() function 
  
- range(n) ==> n values from 0 to n-1 
- range(4) ==> 0,1,2,3 
  
1. range(m,n)==> from m to n-1 
- range(2,7)==> 2,3,4,5,6 
  
1. range(begin,end,step) 
- range(1,11,1) ==> 1,2,3,4,5,6,7,8,9,10 
- range(1,11,2) ==> 1,3,5,7,9 
- range(1,11,3) ==> 1,4,7,10

In [27]:
# only stop value ==> 0 to stop-1 
import numpy as np 
a = np.arange(10)    

print(f'a ==> {a}') 
print(f'The dimensions of the array a ==> {a.ndim}') 
print(f'The data type of elements of array a ==> {a.dtype}') 
print(f'The size of the array a ==> {a.size}') 
print(f'The shape of the array a ==> {a.shape}') 

a ==> [0 1 2 3 4 5 6 7 8 9]
The dimensions of the array a ==> 1
The data type of elements of array a ==> int32
The size of the array a ==> 10
The shape of the array a ==> (10,)


In [28]:
# both start and stop values: start to stop-1 
import numpy as np 
a = np.arange(1,11)   
print(f'a ==> {a}') 
print(f'The dimensions of the array a ==> {a.ndim}') 
print(f'The data type of elements of array a ==> {a.dtype}') 
print(f'The size of the array a ==> {a.size}') 
print(f'The shape of the array a ==> {a.shape}')

a ==> [ 1  2  3  4  5  6  7  8  9 10]
The dimensions of the array a ==> 1
The data type of elements of array a ==> int32
The size of the array a ==> 10
The shape of the array a ==> (10,)


In [31]:
# start, stop and step values : start to stop-1 with step 
import numpy as np 
a = np.arange(1,11,2)  
print(f'a ==> {a}') 
print(f'The dimensions of the array a ==> {a.ndim}') 
print(f'The data type of elements of array a ==> {a.dtype}') 
print(f'The size of the array a ==> {a.size}') 
print(f'The shape of the array a ==> {a.shape}')

a ==> [1 3 5 7 9]
The dimensions of the array a ==> 1
The data type of elements of array a ==> int32
The size of the array a ==> 5
The shape of the array a ==> (5,)


In [32]:
# with a particular datatype of the elements 
import numpy as np 
a = np.arange(1,11,3,dtype=float) 
print(f'a ==> {a}') 
print(f'The dimensions of the array a ==> {a.ndim}') 
print(f'The data type of elements of array a ==> {a.dtype}') 
print(f'The size of the array a ==> {a.size}') 
print(f'The shape of the array a ==> {a.shape}') 

a ==> [ 1.  4.  7. 10.]
The dimensions of the array a ==> 1
The data type of elements of array a ==> float64
The size of the array a ==> 4
The shape of the array a ==> (4,)


`linspace()` 
- same as arange() only but in the specified interval, linearly spaced values 
```python
linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0) 
    Return evenly spaced numbers over a specified interval. 
     
    Returns `num` evenly spaced samples, calculated over the 
    interval [`start`, `stop`].
```
linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0) 
- Both start and stop are includded because endpoint=True 
- If endpoint=False then stop is excluded 
- retstep denotes the spacing between the points.If True then the value is returned 
- calculation of spacing (stop-start)/(num-1) if endpoint=True 
- calculation of spacing (stop-start)/(num) if endpoint=False     

In [34]:
# 50 evenly spaced values between 0 and 1 are returned including both 0 and 1 
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [35]:
# 4 evenly spaced valued between 0 and 1 including 0 and 1 
np.linspace(0,1,4) 

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [36]:
# 4 evenly spaced valued between 0 and 1 including 0 and excluding 1 
np.linspace(0,1,4,endpoint=False)

array([0.  , 0.25, 0.5 , 0.75])

In [38]:
# 4 evenly spaced valued between 0 and 1 including 0 and excluding 1 and return spacing 
np.linspace(0,1,4,endpoint=False,retstep=True)

(array([0.  , 0.25, 0.5 , 0.75]), 0.25)

In [39]:
# 10 values between 1 to 100 including 1 and 100 with equally spaced int values 
np.linspace(1,100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

#### `arange()` vs `linspace()` 
- arange() ==> Elements will be considered in the given range based on step value. 
- linspace() ==> The specified number of values will be considered in the given 
range. 
### `zeros` 
- array is filled with 0s 

In [42]:
import numpy as np
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



### Multidimensional Arrays

**0-D Array (Scalar):** A single value.

**1-D Array (Vector):** A collection of 0-D arrays.

**2-D Array (Matrix):** A collection of 1-D arrays.

**3-D Array (Tensor):** A collection of 2-D arrays.

**Examples:**

* **(10,)**: A 1-D array containing 10 elements.
* **(5, 2)**: A 2-D array containing 5 rows and 2 columns.
* **(2, 3, 4)**: A 3-D array with:
    * 2 2-D arrays
    * Each 2-D array has 3 rows
    * Each 2-D array has 4 columns
    * Total size: 2 * 3 * 4 = 24


In [43]:
# zeros(shape, dtype=float, order='C', *, like=None) ==> shape always in tuple form 
# 1-D array with zeros 
np.zeros(4)

array([0., 0., 0., 0.])

In [45]:
# 2-D arrays with zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
# 3-D array 
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Note: observe the above output.

- outermost there are 3 square brackets are present means it is 3-D array 
- exclude one outermost bracket then it is a 2-D array ==> total 2 2-D arrays present 
- Each 2-D array contains 1-D arrays. Each 2-D contains 3-rows and 4-columns

In [47]:
# 4-D array ==> collection of 3-D arrays 
# (2,2,3,4)  
# 2 ==> no. of 3-D arrays 
# 2 ==> every 3-D 2 2-D arrays 
# 3 ==> Every 2-D array contains 3 rows 
# 4 ==> every 2-D array contains 4 columns 
np.zeros((2,2,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

### `ones()` 
- exactly same as zeros except array is filled with 1

In [48]:
#1-D array
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
# 2D array
np.ones((5,2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [50]:
# 3-D array 
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

`full` 
- Return a new array of given shape and type, filled with fill_value.

In [51]:
# 1-D array 
np.full(10,fill_value=2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [52]:
# 2-D array 
np.full((2,3),fill_value=3)

array([[3, 3, 3],
       [3, 3, 3]])

In [53]:
# 3-D array 
np.full((2,3,4),fill_value=8) 

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [54]:
# All of the following will give same results 
# • np.full(shape=(2,3,4),fill_value=8) 
# • np.full((2,3,4),fill_value=8) 
# • np.full((2,3,4),8)

`eye()` 
- To generate identity matrix 
- Return a 2-D array with ones on the diagonal and zeros elsewhere.

`eye()` Function in NumPy

**Purpose:**
* Creates a 2-D array with ones on the diagonal and zeros elsewhere.

**Parameters:**

* **N:** Number of rows in the output.
* **M:** Number of columns in the output. If `None`, defaults to `N`.
* **k:** Index of the diagonal:
  * 0 (default): Main diagonal.
  * Positive: Upper diagonal.
  * Negative: Lower diagonal.
* **dtype:** Data-type of the returned array.
* **order:** Memory storage order:
  * 'C': Row-major (C-style).
  * 'F': Column-major (Fortran-style).

**Example:**

```python
import numpy as np

# Create a 3x3 identity matrix
matrix = np.eye(3)
print(matrix)
```

**Output:**

```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

- Function Arguments in Python

**Positional Arguments:**
* Passed based on their position in the function call.

**Keyword Arguments:**
* Passed using `key=value` syntax, where `key` is the argument name and `value` is the value.


**`/` and `*` in Function Definitions:**

* **`f(a, /, b)`:** `a` must be a positional argument. `b` can be positional or keyword.
* **`f(a, *, b)`:** `a` can be positional or keyword. `b` must be a keyword argument.

**Example:**

```python
def my_func(a, /, b, *, c):
    # ...

my_func(1, 2, c=3)  # Valid
my_func(1, b=2, c=3)  # Valid
my_func(1, 2, 3)  # Invalid (c must be a keyword argument)
```


In [55]:
# both positional and keywrod arguments 
def f(a,b): 
    print(f'The value of a :: {a}') 
    print(f'The value of b :: {b}')    
f(10,20) 
f(a=10,b=20)

The value of a :: 10
The value of b :: 20
The value of a :: 10
The value of b :: 20


In [56]:
def f1(a, /,b): 
    print(f'The value of a :{a}') 
    print(f'The value of b :{b}') 
print("Calling f1(10,20)==> Valid") 
f1(10,20)  # valid 
print("Calling f1(a=10,b=20) ==> Invalid") 
f1(a=10,b=20)  
# invalid because before '/' the value for variable should be passed as positional only 

Calling f1(10,20)==> Valid
The value of a :10
The value of b :20
Calling f1(a=10,b=20) ==> Invalid


TypeError: f1() got some positional-only arguments passed as keyword arguments: 'a'

In [57]:
def f1(a,*,b): 
    print(f'The value of a :: {a}') 
    print(f'The value of b :: {b}')  
f1(a=10,b=50) #valid 
f1(10,20)  
# invalid because after '*' we have to provide value for variable(b) through keyword only

The value of a :: 10
The value of b :: 50


TypeError: f1() takes 1 positional argument but 2 were given

![img](./images/digonal.png)

In [58]:
np.eye(2,3) 


array([[1., 0., 0.],
       [0., 1., 0.]])

In [59]:
np.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [60]:
np.eye(5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### `eye()` Properties
1. It always returns a 2-D array.
2. The number of rows and columns need not be the same.
3. If we omit the 'M' value, the number of columns will be the same as 'N'.
4. By default, the main diagonal contains 1s, but we can customize which diagonal contains 1s.

### `identity()` Properties
- It is exactly the same as the `eye()` function except:
1. It is always a square matrix (the number of rows and columns is always the same).
2. Only the main diagonal contains 1s.


In [61]:
# identity(n, dtype=None, *, like=None) 
np.identity(3,dtype=int) 

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])


### `diag()` Properties
- `diag(v, k=0)` ==> Extract a diagonal or construct a diagonal array.

1. **For a 2-D array**: It extracts the elements at the k-th diagonal.
2. **For a 1-D array**: It constructs a diagonal array with the provided elements, and the remaining elements are filled with zeros.


In [62]:
# Extract 2-D diagonal elements 
a = np.arange(1,10).reshape(3,3) 
print(f"Original 3-D array ==> \n {a}") 
print(f"Elements prsent at 0-diagonal ==> {np.diag(a,k=0)}") 
print(f"Elements prsent at 1-diagonal ==> {np.diag(a,k=1)}") 
print(f"Elements prsent at 2-diagonal ==> {np.diag(a,k=2)}") 
print(f"Elements prsent at -1-diagonal ==> {np.diag(a,k=-1)}") 
print(f"Elements prsent at -2-diagonal ==> {np.diag(a,k=-2)}") 
print(f"Elements prsent at 3-diagonal ==> {np.diag(a,k=3)}")

Original 2-D array ==> 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Elements prsent at 0-diagonal ==> [1 5 9]
Elements prsent at 1-diagonal ==> [2 6]
Elements prsent at 2-diagonal ==> [3]
Elements prsent at -1-diagonal ==> [4 8]
Elements prsent at -2-diagonal ==> [7]
Elements prsent at 3-diagonal ==> []


In [63]:
# 1-D construct 2-D array with the diagonal array with the provided elements 
# remaining elements are filled with zeros 
a = np.array([10,20,30,40]) 
np.diag(a,k=0)

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [64]:
np.diag(a,k=1) 

array([[ 0, 10,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 30,  0],
       [ 0,  0,  0,  0, 40],
       [ 0,  0,  0,  0,  0]])

In [65]:
np.diag(a,k=-1) 

array([[ 0,  0,  0,  0,  0],
       [10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 40,  0]])