In [7]:
import numpy as np

In [1]:
list = [1,2,3]

In [2]:
list*2

[1, 2, 3, 1, 2, 3]

In [4]:
list+list

[1, 2, 3, 1, 2, 3]

In [9]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [10]:
type(arr1)

numpy.ndarray

In [11]:
arr1*2

array([2, 4, 6])

In [13]:
a=1

In [14]:
arr1.shape

(3,)

In [15]:
arr1.ndim

1

In [16]:
np.arange(1,5)

array([1, 2, 3, 4])

In [17]:
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [19]:
np.array(np.arange(1,10.5, 0.5))

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [20]:
[1,2,3,4.0]

[1, 2, 3, 4.0]

In [21]:
np.array([1,2,3,4.0])

array([1., 2., 3., 4.])

In [22]:
np.array([1,2,3,4], dtype="int8")

array([1, 2, 3, 4], dtype=int8)

In [23]:
np.array([1000,2,3,4], dtype="int8")

C:\Users\Admin\AppData\Local\Temp\ipykernel_17604\3954496770.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 1000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([1000,2,3,4], dtype="int8")


array([-24,   2,   3,   4], dtype=int8)

In [25]:
np.array([100**4, 2,4])

array([100000000,         2,         4])