In [2]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
class Classifier(object):
    def __init__(self):
        self.w=None
        self.b=None

    def sgmoid(self, x):
        return 1/(1+np.exp(-x))

    def fit(self, x, y, epochs=300, eta=0.01):
        self.w=np.zeros(shape=(x.shape[1], 1))
        self.b=0
        for _ in range(epochs):
            for idx, ip in enumerate(x):
                ip.ip.reshape(-1, 1)
                target=y[idx]
                pred=self.w.T@ip+self.b 
                pred=pred.reshape(-1)
                pred=pred[0]
                pred=1 if self.sigmod(pred)>0.5 else -1
                gradient=pred-target
                self.w-=eta*gradient*ip                
                self.b-=eta*gradient


    def predict(self, x):
        pred_list=[]
        for ip in x:
            ip=ip.reshape(-1, 1)
            pred=self.w.T@ip+self.b 
            pred=pred.reshape(-1)
            pred=pred[0]
            pred=pred_list.append(pred)

        return pred_list

In [4]:
iris_df=load_iris()
X=iris_df["data"]
y=iris_df["target"]

In [5]:
X = (X-X.mean(axis=0)/X.std(axis=0))

In [8]:
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2)

In [9]:
    # class encoding
    # 0 - setosa
    # 1 - versicolor
    # 2 - virginica
    # first recongnise setosa vs non setosa
    # second recognise versicolor vs non versicolor
    # third recognise virginica vs non verginica
    # clf_1 -> recognise only setosa and non setosa


In [ ]:
clf_1 = Classifier()

In [10]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

np.random.seed(42)  # Set seed for reproducibility


class BinaryClassifier:
    """
    A simple binary classifier using gradient descent for weight and bias updates.
    """
    def __init__(self):
        self.weights = None  # Model weights
        self.bias = None  # Model bias

    def fit(self, X, y, epochs=300, learning_rate=0.01):
        """
        Train the binary classifier using gradient descent.
        """
        # Initialize weights and bias
        self.weights = np.zeros(shape=(X.shape[1], 1))
        self.bias = 0

        for _ in range(epochs):  # Loop over the number of epochs
            for idx, sample in enumerate(X):
                sample = sample.reshape(-1, 1)
                target = y[idx]

                # Linear model output
                raw_prediction = (self.weights.T @ sample + self.bias).item()
                predicted_class = 1 if self.sigmoid(raw_prediction) > 0.5 else -1

                # Calculate gradient
                error = predicted_class - target
                self.weights -= learning_rate * error * sample
                self.bias -= learning_rate * error

    def sigmoid(self, x):
        """
        Sigmoid activation function.
        """
        return 1 / (1 + np.exp(-x))

    def predict(self, X):
        """
        Predict the class labels for input data X.
        """
        predictions = []
        for sample in X:
            sample = sample.reshape(-1, 1)
            raw_prediction = (self.weights.T @ sample + self.bias).item()
            predicted_class = 1 if raw_prediction > 0 else -1
            predictions.append(predicted_class)
        return predictions


def main():
    # Load the Iris dataset
    iris_data = load_iris()
    features = iris_data["data"]
    labels = iris_data["target"]

    # Standardize the feature data
    features = (features - features.mean(axis=0)) / features.std(axis=0)

    # Split into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

    # Train classifiers for each class (one-vs-all approach)
    classifiers = []
    for class_label in range(3):
        binary_labels = np.where(y_train == class_label, 1, -1)  # Encode labels for the current class
        classifier = BinaryClassifier()
        classifier.fit(X_train, binary_labels, epochs=300, learning_rate=0.01)
        classifiers.append(classifier)

    # Predict for each classifier and evaluate
    final_predictions = []
    for idx, sample in enumerate(X_test):
        binary_results = [clf.predict([sample])[0] for clf in classifiers]
        # Map binary results to class labels
        if binary_results == [1, -1, -1]:
            final_predictions.append(0)
        elif binary_results == [-1, 1, -1]:
            final_predictions.append(1)
        elif binary_results == [-1, -1, 1]:
            final_predictions.append(2)
        else:
            # Handle undefined cases randomly
            final_predictions.append(np.random.choice([0, 1, 2]))

    # Calculate the accuracy of the final predictions
    print("Final Accuracy: ", accuracy_score(y_test, final_predictions))


if __name__ == "__main__":
    main()


Final Accuracy:  0.7666666666666667


In [11]:
import numpy as np

sample = np.array([2, 3, 4])  # A 1D array
print("Original Shape:", sample.shape)
# Output: (3,) -> 1D array with 3 elements


Original Shape: (3,)


In [12]:
reshaped_sample = sample.reshape(-1, 1)
print(reshaped_sample)
print("Reshaped Shape:", reshaped_sample.shape)


[[2]
 [3]
 [4]]
Reshaped Shape: (3, 1)


In [13]:
import numpy as np

# Create a row vector with 1 row and 10 columns
row_vector = np.array([np.arange(1, 11)])  # Numbers from 1 to 10
print("Row Vector:")
print(row_vector)
print("Shape:", row_vector.shape)

Row Vector:
[[ 1  2  3  4  5  6  7  8  9 10]]
Shape: (1, 10)


In [14]:
# Create a column vector with 10 rows and 1 column
column_vector = np.array(np.arange(1, 11)).reshape(-1, 1)  # Numbers from 1 to 10
print("\nColumn Vector:")
print(column_vector)
print("Shape:", column_vector.shape)



Column Vector:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
Shape: (10, 1)


In [15]:
# Large Row Vector
large_row_vector = np.array([np.arange(1, 1001)])
print("\nLarge Row Vector Shape:", large_row_vector.shape)

# Large Column Vector
large_column_vector = np.array(np.arange(1, 1001)).reshape(-1, 1)
print("Large Column Vector Shape:", large_column_vector.shape)



Large Row Vector Shape: (1, 1000)
Large Column Vector Shape: (1000, 1)


In [16]:
import numpy as np

# Define a 3x3 matrix
matrix = np.array([[2, 4, 6],
                   [1, 3, 5],
                   [7, 9, 11]])

# Define a 3x1 column vector
column_vector = np.array([[1],
                          [2],
                          [3]])

# Perform the multiplication
result = np.dot(matrix, column_vector)

print("Matrix:\n", matrix)
print("\nColumn Vector:\n", column_vector)
print("\nResult of Matrix × Column Vector:\n", result)


Matrix:
 [[ 2  4  6]
 [ 1  3  5]
 [ 7  9 11]]

Column Vector:
 [[1]
 [2]
 [3]]

Result of Matrix × Column Vector:
 [[28]
 [22]
 [58]]


In [17]:
# Define a 1x3 row vector
row_vector = np.array([[1, 2, 3]])

# Perform the multiplication
result = np.dot(row_vector, matrix)

print("\nRow Vector:\n", row_vector)
print("\nResult of Row Vector × Matrix:\n", result)



Row Vector:
 [[1 2 3]]

Result of Row Vector × Matrix:
 [[25 37 49]]


In [18]:
# Define another 3x3 matrix
matrix_2 = np.array([[1, 0, 2],
                     [3, 1, 4],
                     [5, 2, 6]])

# Perform the multiplication
result = np.dot(matrix, matrix_2)

print("\nSecond Matrix:\n", matrix_2)
print("\nResult of Matrix × Matrix:\n", result)


Second Matrix:
 [[1 0 2]
 [3 1 4]
 [5 2 6]]

Result of Matrix × Matrix:
 [[ 44  16  56]
 [ 35  13  44]
 [ 89  31 116]]
