In [1]:
import numpy as np

In [2]:
bin(12)

'0b1100'

In [4]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [5]:
vec_bin = np.vectorize(bin)

In [8]:
vec_bin(arr)

array([['0b1', '0b10', '0b11', '0b100'],
       ['0b101', '0b110', '0b111', '0b1000'],
       ['0b1001', '0b1010', '0b1011', '0b1100'],
       ['0b1101', '0b1110', '0b1111', '0b10000']], dtype='<U7')

In [10]:
arr = np.array([int(i) for i in "1 1 2 5 7 6 7 6 3".split()])
arr

array([1, 1, 2, 5, 7, 6, 7, 6, 3])

In [13]:
uniq, freq = np.unique(arr, return_counts=True)

In [14]:
uniq

array([1, 2, 3, 5, 6, 7])

In [15]:
freq

array([2, 1, 1, 1, 2, 2], dtype=int64)

In [16]:
zeros = np.zeros(10, dtype='int')
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
zeros[uniq-1] = freq

In [19]:
zeros

array([2, 1, 1, 0, 1, 2, 2, 0, 0, 0])

In [22]:
def my_dummy(arr):
    uniq, freq = np.unique(arr, return_counts=True)
    zeros = np.zeros(10, dtype='int')
    zeros[uniq-1] = freq

    return zeros

convert = np.vectorize(my_dummy)

In [23]:
# [convert(row) for row in matrix]

In [27]:
# New Question
arr = np.arange(16).reshape(4,4)
arr[0,1] = 2

In [28]:
arr%2==0

array([[ True,  True,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [37]:
res = arr[arr%2==0]
res

array([ 0,  2,  2,  4,  6,  8, 10, 12, 14])

In [38]:
arr[arr%2==0].size

9

In [39]:
size = np.sqrt(arr[arr%2==0].size)
size

3.0

In [40]:
size == int(size)

True

In [41]:
res.reshape(int(size), int(size))

array([[ 0,  2,  2],
       [ 4,  6,  8],
       [10, 12, 14]])

In [43]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
row = np.array([0,1,2])
row

array([0, 1, 2])

In [46]:
mask = np.array([1,0,1,0], dtype=bool)
mask

array([ True, False,  True, False])

In [47]:
row[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [48]:
x[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [49]:
row[:, np.newaxis].shape

(3, 1)

In [6]:
# Original matrix retrival
import numpy as np
a = np.linspace(0,2, num=4).reshape(2,2)
a

array([[0.        , 0.66666667],
       [1.33333333, 2.        ]])

In [7]:
b = np.linspace(5,7, num=4).reshape(2,2)
b

array([[5.        , 5.66666667],
       [6.33333333, 7.        ]])

In [8]:
c = np.linspace(1,3, num=4).reshape(2,2)
c

array([[1.        , 1.66666667],
       [2.33333333, 3.        ]])

In [9]:
d = np.linspace(6,9, num=4).reshape(2,2)
d

array([[6., 7.],
       [8., 9.]])

In [13]:
e = np.hstack((a,b))
e

array([[0.        , 0.66666667, 5.        , 5.66666667],
       [1.33333333, 2.        , 6.33333333, 7.        ]])

In [14]:
f = np.hstack((c,d))
f

array([[1.        , 1.66666667, 6.        , 7.        ],
       [2.33333333, 3.        , 8.        , 9.        ]])

In [16]:
np.vstack((e,f)).round(1)

array([[0. , 0.7, 5. , 5.7],
       [1.3, 2. , 6.3, 7. ],
       [1. , 1.7, 6. , 7. ],
       [2.3, 3. , 8. , 9. ]])

In [17]:
np.bmat?

Signature: np.bmat(obj, ldict=None, gdict=None)
Docstring:
Build a matrix object from a string, nested sequence, or array.

Parameters
----------
obj : str or array_like
    Input data. If a string, variables in the current scope may be
    referenced by name.
ldict : dict, optional
    A dictionary that replaces local operands in current frame.
    Ignored if `obj` is not a string or `gdict` is None.
gdict : dict, optional
    A dictionary that replaces global operands in current frame.
    Ignored if `obj` is not a string.

Returns
-------
out : matrix
    Returns a matrix object, which is a specialized 2-D array.

See Also
--------
block :
    A generalization of this function for N-d arrays, that returns normal
    ndarrays.

Examples
--------
>>> A = np.mat('1 1; 1 1')
>>> B = np.mat('2 2; 2 2')
>>> C = np.mat('3 4; 5 6')
>>> D = np.mat('7 8; 9 0')

All the following expressions construct the same block matrix:

>>> np.bmat([[A, B], [C, D]])
matrix([[1, 1, 2, 2],
        [1, 1, 2,

## Entropy

In [20]:
A = np.array([0,1,0,0,0,1,1,0,0,0,1,0,0,1])

In [26]:
size = A.size
size

14

In [27]:
eles, freq = np.unique(A, return_counts=True)

In [28]:
eles

array([0, 1])

In [29]:
freq

array([9, 5], dtype=int64)

In [31]:
probs = freq/size
probs

array([0.64285714, 0.35714286])

In [34]:
log_prob = np.log(probs)
log_prob

array([-0.44183275, -1.02961942])

In [38]:
-1*np.sum(probs*log_prob)


0.6517565611726531